### ISSUE TITLE
Return StringBuilder

### ISSUE THREAD

**Issue by varnerac** [Olian04/gleam_handles#4]
It'd be nice to return StringBuilders in addition to Strings.

**Comment by Olian04** [comment]
Hi. Thank you for opening an issue.
Could you please clarify which part of the library you are commenting on?
Could you also please provide a code example of a use-case as well as an explanation as to why this use-case is easier/possible with a `StringBuilder` rather than a `String`?

**Comment by varnerac** [comment]
Sure. I'm referring to a version of `run` (`run_builder`?) that returns a `Result(StringBuilder, RuntimeError)`. It's a matter of performance on Erlang runtimes. Erlang ports, like files, sockets, etc. can take deep lists. That's why gleam has `StringBuilder` and `BytesBuilder`. See the documentation for the [string_builder module](https://hexdocs.pm/gleam_stdlib/gleam/string_builder.html) or the [Erlang Efficiency Guide]( https://www.erlang.org/docs/24/efficiency_guide/listhandling#deep-and-flat-lists) for info on it. Essentially you want to allow the user to receive a builder to avoid the unnecessary flattening costs and integrate with other builders going to I/O.

**Comment by Olian04** [comment]
That makes sense. I've never used any other beam language before, so performance optimisations for the beam are new to me. I'll need to do some performance testing and see how big of a difference it makes. But if the impact is big enough i might just swap over to returning a `StringBuilder` instead of a `String` rather than providing a separate function for it.

**Comment by Olian04** [comment]
The internal implementation of the engine now uses `StringBuilder` throughout. However in order to not introduce a breaking change, the top level api still returns a `String`. This might change in the next major version.

**Comment by Olian04** [comment]
@varnerac This change is included in version 4.0.0
